# Generated by Django 4.2.10 on 2024-03-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_cellar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourBooking',
        ),
    ]
