# Generated by Django 4.2.10 on 2024-03-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_cellar', '0002_alter_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['timestamp']},
        ),
    ]
