# Generated by Django 4.2.10 on 2024-03-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_cellar', '0005_alter_galleryimage_image_alter_review_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='image',
            new_name='review_image',
        ),
    ]
