# Generated by Django 4.2.10 on 2024-03-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_cellar', '0007_rename_image_galleryimage_gallery_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='gallery_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_image',
            new_name='image',
        ),
    ]
