# Generated by Django 4.2.10 on 2024-02-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_cellar', '0007_rename_user_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
