# Generated by Django 4.2.10 on 2024-03-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_cellar', '0008_rename_gallery_image_galleryimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(default='placeholder', upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='placeholder', upload_to='gallery/'),
        ),
    ]
