# Generated by Django 4.2.10 on 2024-02-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_cellar', '0008_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_date', models.DateTimeField()),
                ('num_guests', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
