# Generated by Django 4.2.10 on 2024-03-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_cellar', '0010_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
